# Generated by Django 5.2.7 on 2025-11-02 01:55

from decimal import Decimal

from django.db import migrations


def seed_locations(apps, schema_editor):
    Location = apps.get_model('campus', 'Location')

    landmarks = [
        {
            'name': 'Tech Tower',
            'slug': 'tech-tower',
            'description': (
                'Built in 1888, Tech Tower is one of Georgia Tech’s oldest buildings '
                'and is home to the iconic TECH signs that overlook campus.'
            ),
            'latitude': Decimal('33.772602'),
            'longitude': Decimal('-84.394924'),
            'address': '225 North Ave NW, Atlanta, GA 30332',
            'category': 'Historic',
        },
        {
            'name': 'Clough Undergraduate Learning Commons',
            'slug': 'clough-commons',
            'description': (
                'The Clough Commons is a hub for student learning that houses classrooms, labs, '
                'and multiple academic support services.'
            ),
            'latitude': Decimal('33.774647'),
            'longitude': Decimal('-84.396328'),
            'address': '266 4th St NW, Atlanta, GA 30332',
            'category': 'Academic',
        },
        {
            'name': 'Bobby Dodd Stadium',
            'slug': 'bobby-dodd-stadium',
            'description': (
                'Home to the Georgia Tech Yellow Jackets football team and the oldest on-campus '
                'stadium in Division I FBS.'
            ),
            'latitude': Decimal('33.772541'),
            'longitude': Decimal('-84.392852'),
            'address': '177 North Ave NW, Atlanta, GA 30313',
            'category': 'Athletics',
        },
        {
            'name': 'Price Gilbert Library',
            'slug': 'price-gilbert-library',
            'description': (
                'The main library on campus offering study space, research support, and extensive '
                'collections that serve the Georgia Tech community.'
            ),
            'latitude': Decimal('33.774090'),
            'longitude': Decimal('-84.395721'),
            'address': '704 Cherry St NW, Atlanta, GA 30332',
            'category': 'Academic',
        },
        {
            'name': 'Kendeda Building for Innovative Sustainable Design',
            'slug': 'kendeda-building',
            'description': (
                'A Living Building Challenge-certified facility showcasing advanced sustainability '
                'features and interdisciplinary learning spaces.'
            ),
            'latitude': Decimal('33.775734'),
            'longitude': Decimal('-84.395340'),
            'address': '422 Ferst Dr NW, Atlanta, GA 30313',
            'category': 'Sustainability',
        },
        {
            'name': 'John Lewis Student Center',
            'slug': 'john-lewis-student-center',
            'description': (
                'Recently renovated student center featuring dining, event venues, and gathering '
                'spaces for campus organizations.'
            ),
            'latitude': Decimal('33.774044'),
            'longitude': Decimal('-84.398781'),
            'address': '351 Ferst Dr NW, Atlanta, GA 30332',
            'category': 'Student Life',
        },
        {
            'name': 'Ferst Center for the Arts',
            'slug': 'ferst-center-for-the-arts',
            'description': (
                'A performing arts venue that hosts concerts, theater productions, and lectures.'
            ),
            'latitude': Decimal('33.775036'),
            'longitude': Decimal('-84.402077'),
            'address': '349 Ferst Dr NW, Atlanta, GA 30332',
            'category': 'Arts',
        },
    ]

    for landmark in landmarks:
        Location.objects.update_or_create(
            slug=landmark['slug'],
            defaults=landmark,
        )


def unseed_locations(apps, schema_editor):
    Location = apps.get_model('campus', 'Location')
    slugs = [
        'tech-tower',
        'clough-commons',
        'bobby-dodd-stadium',
        'price-gilbert-library',
        'kendeda-building',
        'john-lewis-student-center',
        'ferst-center-for-the-arts',
    ]
    Location.objects.filter(slug__in=slugs).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_locations, unseed_locations),
    ]
