# Generated by Django 5.2.7 on 2025-11-04 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0003_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='historical_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='location',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='locations/'),
        ),
    ]
